### ISSUE TITLE
[seek help]The following error when debugging your code

### ISSUE THREAD

**Issue by xulunfan** [Ian09/CF-NADE#3]
These are error message:
MovieLens1M=/home/xlf/ml_datasets/MovieLens1M-shuffle-itembased-1 python learner_masked_ordinalcost_directly_itembased_newsoftmax_timing.py 512 10 60 0.001 0.1 0.001 1e-8 500 tanh 0 0.02 Adam 0 1 0.995 /home/xlf/CF-NADE  

Epoch 0
Traceback (most recent call last):
  File "learner_masked_ordinalcost_directly_itembased_newsoftmax_timing.py", line 729, in <module>
    cost_value = f_get_grad(inp_r, inp_m, out_r, out_m)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
MemoryError: 
Apply node that caused the error: CumsumOp{2}(rating_cost_sf_apply_output)
Toposort index: 112
Inputs types: [TensorType(float64, 3D)]
Inputs shapes: [(512, 6040, 5)]
Inputs strides: [(241600, 40, 8)]
Inputs values: ['not shown']
Outputs clients: [[Subtensor{::, ::, ::int64}(CumsumOp{2}.0, Constant{-1}), Elemwise{Composite{((i0 - log(i1)) * i2)}}[(0, 0)](Elemwise{log,no_inplace}.0, CumsumOp{2}.0, Subtensor{::, ::, ::int64}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "learner_masked_ordinalcost_directly_itembased_newsoftmax_timing.py", line 651, in <module>
    cost, nll, nll_item_ratings, cost_ordinal_1N, cost_ordinal_N1, prob_item_ratings = rating_cost(y, output_ratings, input_masks, output_masks, D, d, alpha=alpha, std=std)
  File "learner_masked_ordinalcost_directly_itembased_newsoftmax_timing.py", line 53, in rating_cost
    accu_prob_1N = T.extra_ops.cumsum(prob_item_ratings, axis=2)

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

Could you give me some help?Thanks a lot.

**Comment by Ian09** [comment]
It seems you use float64 as the default data type. Try float32 please.
